- README.md
This is the trick that works for a quick start.
> docs(build): Correct url for kustomize build in quick start

- build/kube.mk
Generating manifests (and thus `make install`) was broken in #33 This resolves that by passing the configs dir to `controller-gen` explicitly.
> fix(build): Fix manifest generation with renamed configs dir

- .github/workflows/snapshot.yml
Github action to build/push `snapshot` docker image to docker hub on all master merges.
> Push snapshot docker image on all merges to master

- configs/manager/manager.yaml
When we deployed the operator to a test cluster we found it crashed immediately when we attempted to `kubectl apply -f ...` with the example policy.
It didn't take much extra memory to get it working.
> fix(config): increase memory for operator

- configs/rbac/role.yaml
updates rbac permissions to add the built in k8 operator roles access to manage our CRDs
> bug: update rbac permissions

- controllers/policy_controller.go
- go.mod
This PR contains a small refactoring to reduce the size of the `createOrUpdateConditions` method in `policy_controller.go`.
> chore: refactor createOrUpdateConditions into two smaller methods

- README.md
- build/docker.mk
- build/kube.mk
- configs/manager/kustomization.yaml
In light of updating the Docker Hub name to be `newrelic/kubernetes-operator`, we need to update some additional refs to the old name `newrelic/k8s-operator`.
> chore: update refs of "k8s-operator" to "kubernetes-operator"

- cmd/manager/main.go
Seems to be required with the current version of controller-runtime.
> fix: set LeaderElectionID

- .github/workflows/test.yml
- build/lint.mk
Github was not linting commit messages correctly as it does a shallow checkout by default.
> chore(build): Force Github to fetch all history for linting, reset date

- README.md
- configs/development/kustomization.yaml
We build and tag a :snapshot image with every merge to master.
This kustomization makes it trivial to use that image.
kustomize build configs/development | kubectl apply -f -
Co-authored-by: Shane Delight <sdelight@newrelic.com>
> chore(build): devs can use newrelic/kubernetes-operator:snapshot

- scripts/release.sh
Updates the version used by the manager docker image to line up with the version number published by goreleaser.
> match release manager docker image tag with goreleaser

- configs/webhook/manifests.yaml
fixes a whitespace issue that somehow crept in on the last PR. It simply removed 2 spaces of whitespace from each line in the file
> bug: fix webhook manifest whitespace

- build/compile.mk
This addresses something overlooked in the prior PR where the compile step was happily creating no binaries and not throwing an error and wasn't caught until the build system attempted to create a new docker image but no binary was present.
> refactor(build): adjusts build system for main.go in project root

- .goreleaser.yml
Updates goreleaser to use a binary from the root directory as needed by kubebuilder
> chore: update goreleaser for local directory binary

- CHANGELOG.md
- config/manager/kustomization.yaml
Release for 0.0.4. No change vs 0.0.3 other than fixing the build system that prevented properly publishing the 0.0.3 release.
> chore(release): Updates for v0.0.4

- config/manager/manager.yaml
The current instructions / default config create a "system" namespace, and then fail to add the operator to "newrelic-kubernetes-operator-system" namespace.  This adds the correct namespace.
> fix: update manager namespace created

- controllers/alerts_apmcondition_controller.go
- controllers/alerts_nrqlcondition_controller.go
- controllers/alerts_policy_controller.go
- controllers/alertschannel_controller.go
- controllers/apmalertcondition_controller.go
- controllers/nrqlalertcondition_controller.go
- controllers/policy_controller.go
The initial idea in this PR was to surface the underlying errors that happen when `r.Client.Get()`ing an object from the API which is not found. So i.e. if we try to get a non-existing `Secret` we'll now get the actual error instead of a misleading `api key is blank` error.
Additionally, all `Reconcile()` functions now return `ctrl.Request{}, err` when a `r.Client.Get()` error occurs, thus making use of the retry mechanism which is [built-in into the controller](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L263-L281).
However, some of the strict pre-commit hooks started not passing because of a cyclomatic complexity of 21 in some `Reconcile()` functions, so I ultimately refactored a bunch of them. I basically moved the resource …
> chore: surface errors, requeue, refactor

- controllers/alerts_policy_controller.go
- controllers/alerts_policy_controller_integration_test.go
This adds owner resource annotations for policy created apm and NRQL AlertsCondition objects.
> feat: add parent kubernetes object references

- config/manager/manager.yaml
fix: namespace's prefix deleted(manager.yaml)
> fix: namespace's prefix deleted(manager.yaml)

- .github/workflows/compile.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/test.yml
fixes https://github.com/newrelic/newrelic-kubernetes-operator/issues/125 by addressing github's deprecation of the `add-path` command
> chore(build): update workflows to avoid deprecated add-path

- README.md
We recently added newrelic-k8s-operator which is an operator for managing New Relic's Kubernetes integration. This updates the README to direct users to the right place if that is what they were looking for.
> chore(docs): Update README to add differentiation with newrelic-k8s-operator

- README.md
updated readme to point to new k8s-operator repo
> docs: update readme to point to new k8s-operator repo
